### ISSUE TITLE
Create sample boards

### ISSUE THREAD

**Issue by KubaPawlak** [KubaPawlak/15-puzzle-solver#16]
Prepare a list of example boards of size 3x3 with varying required number of moves, and place them inside `benches::shared::create_sample_boards` function.

Also prepare a few 4x4 boards in a separate txt file, also with varying required number of moves.

**Comment by julek987** [comment]
[Boards.txt](https://github.com/KubaPawlak/15-puzzle-solver/files/13624864/Boards.txt)
